app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('interface', __name__, url_prefix='/interface')

from . import routes, models

app/blueprints/api/routes.py
from . import bp as api
from flask import render_template, redirect, url_for, jsonify, request
import requests
from app import db
from app.blueprints.database.models import User, Role, Project, BlogPost, Tag, Page, PageCategory, PageComponent, ComponentElement

@api.route('/', methods=['GET'])
def main():
    context = {
        'users': User.query.all(),
        'blogposts': BlogPost.query.all(),
        'projects': Project.query.all(),
        'tags': Tag.query.all()
    }
    return render_template('api/main.html', **context)

@api.route('/all_users', methods=['GET'])
def all_users():
    all_users = [user.to_dict() for user in User.query.all()]
    return jsonify(all_users)

@api.route('/single_user', methods=['GET'])
def single_user():
    this_user = User.query.get(request.args.get('user_id')).to_dict()
    return jsonify(this_user)

@api.route('/all_blogposts', methods=['GET'])
def all_blogposts():
    all_blogposts = [blogpost.to_dict() for blogpost in BlogPost.query.all()]
    for blogpost in all_blogposts:
        blogpost['author'] = User.query.get(blogpost['author']).username
    return jsonify(all_blogposts)

@api.route('/single_blogpost', methods=['GET'])
def single_blogpost():
    this_blogpost = BlogPost.query.get(request.args.get('blogpost_id')).to_dict()
    this_blogpost['author'] = User.query.get(this_blogpost['author']).username
    return jsonify(this_blogpost)

@api.route('/all_projects', methods=['GET'])
def all_projects():
    all_projects = [project.to_dict() for project in Project.query.all()]
    return jsonify(all_projects)

@api.route('/single_project', methods=['GET'])
def single_project():
    this_project = Project.query.get(request.args.get('project_id')).to_dict()
    return jsonify(this_project)

@api.route('/all_tags', methods=['GET'])
def all_tags():
    all_tags = [tag.to_dict() for tag in Tag.query.all()]
    return jsonify(all_tags)

@api.route('/single_tag', methods=['GET'])
def single_tag():
    this_tag = Tag.query.get(request.args.get('tag_id')).to_dict()
    return jsonify(this_tag)

###################
## Site API V0.2 ##
###################

# Page Routes

# All Pages
@api.route('/all_pages', methods=['GET'])
def all_pages():
    return jsonify([page.to_dict() for page in Page.query.all()])

# Single Page
@api.route('/get_page', methods=['GET'])
def get_page():
    return jsonify(Page.query.get(request.args.get('page_id')).to_dict())

app/templates/api/main.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <h5 class="page_title">Alexander Blair's Portfolio API Docs and Requests</h5>
</div>
<div class="row">
    <div>
        <h5>Request Alls</h5>
    </div>
    <ul>
        <a href="{{ url_for('interface.all_users') }}">
            <li>
                Users
            </li>
        </a>
    </ul>
</div>

<div class="row">
    <div>
        <h5>Single Entities</h5>
    </div>
    <form action="{{ url_for('interface.single_user') }}">
        <div>
            <h5>User</h5>
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="user_id">Users</label>
            </div>
            <select class="custom-select" id="user_id" name="user_id">
                {% for user in users %}
                    <option value="{{ user.id }}">{{ user.username }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Select User</button>
    </form>
    <form action="{{ url_for('interface.single_blogpost') }}">
        <div>
            <h5>Blog Posts</h5>
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="blogpost_id">Posts</label>
            </div>
            <select class="custom-select" id="blogpost_id" name="blogpost_id">
                {% for blogpost in blogposts %}
                    <option value="{{ blogpost.id }}">{{ blogpost.title }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Select Post</button>
    </form>
    <form action="{{ url_for('interface.single_project') }}">
        <div>
            <h5>Projects</h5>
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="project_id">Projects</label>
            </div>
            <select class="custom-select" id="project_id" name="project_id">
                {% for project in projects %}
                    <option value="{{ project.id }}">{{ project.name }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Select Project</button>
    </form>
    <form action="{{ url_for('interface.single_tag') }}">
        <div>
            <h5>Tags</h5>
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="tag_id">Tags</label>
            </div>
            <select class="custom-select" id="tag_id" name="tag_id">
                {% for tag in tags %}
                    <option value="{{ tag.id }}">{{ tag.name }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Select Tag</button>
    </form>
</div>
{% endblock content %}