app/blueprints/database/__init__.py
from flask import Blueprint

bp = Blueprint('database', __name__, url_prefix='/database')

from . import routes, models

app/blueprints/database/routes.py
from . import bp as database
from flask import render_template, redirect, url_for, jsonify, request
import requests
from app import db
from .models import User, Role, Project, BlogPost, Tag, Page, PageCategory, PageComponent, ComponentElement
from datetime import datetime as dt

@database.route('/', methods=['GET'])
def main():
    return render_template('database/main.html')

# Database Row Creation

@database.route('/new_entities', methods=['GET', 'POST'])
def new_entities():
    return render_template('database/new_entities.html')

@database.route('/create_role', methods=['GET'])
def create_role():
    new_role = Role()
    role_data = {
        'name' : request.args.get('role_name', None)
    }
    new_role.set_attributes(role_data)
    new_role.new_to_database()
    this_role = Role.query.filter_by(name=new_role.name).first().to_dict()
    return jsonify(this_role)

@database.route('/roles', methods=['GET'])
def roles():
    all_roles = [role.to_dict() for role in Role.query.all()]
    return jsonify(all_roles)

@database.route('/create_user', methods=['GET'])
def create_user():
    new_user = User()
    user_data = {
        'username' : request.args.get('username', None),
        'password' : request.args.get('password', None),
        'email' : request.args.get('email', None),
        'role' : request.args.get('role_id', None),
    }
    new_user.set_attributes(user_data)
    new_user.new_to_database()
    this_user = User.query.filter_by(username=new_user.username).first().to_dict()
    return jsonify(this_user)

@database.route('/users', methods=['GET'])
def users():
    all_users = [user.to_dict() for user in User.query.all()]
    return jsonify(all_users)

@database.route('/create_project', methods=['GET'])
def create_project():
    new_project = Project()
    project_data = {
        'name':request.args.get('project_name', None),
        'description':request.args.get('project_description', None),
        'github':request.args.get('project_github', None)
    }
    new_project.set_attributes(project_data)
    new_project.new_to_database()
    this_project = Project.query.filter_by(name=new_project.name).first().to_dict()
    return jsonify(this_project)

@database.route('/projects', methods=['GET'])
def projects():
    all_projects = [project.to_dict() for project in Project.query.all()]
    return jsonify(all_projects)

@database.route('/create_blogpost', methods=['GET'])
def create_blogpost():
    new_blogpost = BlogPost()
    blogpost_data = {
        'title': request.args.get('blogpost_title', None),
        'content': request.args.get('blogpost_content', None),
        'author': request.args.get('blogpost_author', None)
    }
    new_blogpost.set_attributes(blogpost_data)
    new_blogpost.new_to_database()
    this_blogpost = BlogPost.query.filter_by(title=new_blogpost.title).first().to_dict()
    return jsonify(this_blogpost)

@database.route('/blogposts', methods=['GET'])
def blogposts():
    all_blogposts = [blogpost.to_dict() for blogpost in BlogPost.query.all()]
    return jsonify(all_blogposts)

@database.route('/create_tag', methods=['GET'])
def create_tag():
    new_tag = Tag()
    tag_data = {
        'name': request.args.get('tag_name', None)
    }
    new_tag.set_attributes(tag_data)
    new_tag.new_to_database()
    this_tag = Tag.query.filter_by(name=new_tag.name).first().to_dict()
    return jsonify(this_tag)

@database.route('/tags', methods=['GET'])
def tags():
    all_tags = [tag.to_dict() for tag in Tag.query.all()]
    return jsonify(all_tags)

# Database Row Manipulation
@database.route('/edit_entities', methods=['GET', 'POST'])
def edit_entities():
    context = {
        'blog_posts':[blog_post for blog_post in BlogPost.query.all()],
        'users': [user for user in User.query.filter(User.id > 1).all()],
        'projects': [project for project in Project.query.all()]
    }
    return render_template('database/edit_entities.html', **context)

@database.route('/choose_blogpost', methods=['GET', 'POST'])
def choose_blogpost():
    context = {
        'selected_post': BlogPost.query.get(request.args.get('blogpost_id'))
    }
    return render_template('database/edit_blogpost.html', **context)

@database.route('/edit_blogpost', methods=['GET'])
def edit_blogpost():
    this_post = BlogPost.query.get(request.args.get('blogpost_id'))
    if request.args.get('delete') == 'yes':
        this_post.remove_from_database()
        return f'Blog Post - {this_post.title} - Deleted'
    else:
        new_data = {
            'title': request.args.get('edited_blogpost_title', None),
            'content': request.args.get('edited_blogpost_content', None),
            'last_edit': dt.utcnow()
        }
        this_post.set_attributes(new_data)
        this_post.update_in_database()
        return f'Blog Post - {this_post.title} - Edited'

@database.route('/choose_user', methods=['GET', 'POST'])
def choose_user():
    context = {
        'selected_user': User.query.get(request.args.get('user_id')),
        'roles': Role.query.all()
    }
    return render_template('database/edit_user.html', **context)

@database.route('/edit_user', methods=['GET'])
def edit_user():
    this_user = User.query.get(request.args.get('user_id'))
    if request.args.get('delete') == 'yes':
        this_user.remove_from_database()
        return f'User - {this_user.username} - Deleted'
    else:
        new_data = {
            'username':request.args.get('edited_username', None),
            'password':request.args.get('edited_password', None),
            'role':request.args.get('edited_role', None),
            'last_edit': dt.utcnow()
        }
        this_user.set_attributes(new_data)
        this_user.update_in_database()
        return f'User - {this_user.username} - Edited'

@database.route('/choose_project', methods=['GET', 'POST'])
def choose_project():
    context = {
        'selected_project': Project.query.get(request.args.get('project_id')),
    }
    return render_template('database/edit_project.html', **context)

@database.route('/edit_project', methods=['GET'])
def edit_project():
    this_project = Project.query.get(request.args.get('project_id'))
    if request.args.get('delete') == 'yes':
        this_project.remove_from_database()
        return f'Project - {this_project.name} - Deleted'
    else:
        new_data = {
            'name':request.args.get('edited_name', None),
            'description':request.args.get('edited_description', None),
            'github':request.args.get('edited_github', None),
            'last_edit': dt.utcnow()
        }
        this_project.set_attributes(new_data)
        this_project.update_in_database()
        return f'Project - {this_project.name} - Edited'

@database.route('/change_tags', methods=['GET'])
def change_tags():
    tag_arguments = request.args.get('new_tags').lower().split(', ')
    tag_list = []
    for tag_name in tag_arguments:
        if Tag.query.filter_by(name=tag_name).first() == None:
            new_tag = Tag()
            tag_data = {
                'name': tag_name
            }
            new_tag.set_attributes(tag_data)
            new_tag.new_to_database()
            tag_list.append(Tag.query.filter_by(name=tag_name).first())
        else:
            tag_list.append(Tag.query.filter_by(name=tag_name).first())
    if request.args.get('object_type') == 'project':
        this_object = Project.query.get(request.args.get('object_id'))
        this_object.tags = tag_list
        db.session.commit()
    elif request.args.get('object_type') == 'blogpost':
        this_object = BlogPost.query.get(request.args.get('object_id'))
        this_object.tags = tag_list
        db.session.commit()
    return redirect(url_for('database.main'))

@database.route('/edit_tags', methods=['GET', 'POST'])
def edit_tags():
    selection_list = []
    selection_type = ''
    if request.args.get('object_type') == 'project':
        selection_type = "project"
        selection_list = Project.query.all()
    elif request.args.get('object_type') == 'blogpost':
        selection_type = "blogpost"
        selection_list = BlogPost.query.all()
    context = {
        'selection_type':selection_type,
        'selection_options':selection_list,
        'selection_tags':[]
    }
    return render_template('database/edit_tags.html', **context)

###################
## Site API V0.2 ##
###################

# Start: Entity Selection

@database.route('/v2_new_entities', methods=['GET', 'POST'])
def v2_new_entities():
    return render_template('database/v2_new_entities.html')

@database.route('/v2_edit_entities', methods=['GET', 'POST'])
def v2_edit_entities():
    context = {
        'pages':Page.query.all(),
        'categories':PageCategory.query.all(),
        'components':PageComponent.query.all(),
        'elements':ComponentElement.query.all()
    }
    return render_template('database/v2_edit_entities.html', **context)


# End: Entity Selection

####################

# Start: Page Routes

# @database.route('/create_page_form', methods=['GET', 'POST'])
# def create_page_form():
#     return render_template('database/create_page_form.html')

@database.route('/create_page', methods=['GET'])
def create_page():
    page_name = request.args.get('page_name')

    page_data = {
        'name':page_name,
    }

    if len(request.args.get('page_category')) > 0:
        this_category = PageCategory.query.filter_by(name=request.args.get('page_category')).first()
        page_data['page_category'] = this_category.id

    new_page = Page()
    new_page.set_attributes(page_data)
    new_page.new_to_database()
    this_page = Page.query.filter_by(name=new_page.name).first()


app/templates/database/edit_blogpost.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <form action="{{ url_for('database.edit_blogpost') }}" id="edit_blogpost_form">
        <div>
            <h5>Edit Post: {{ selected_post.title }}</h5>
        </div>
        <div class="form-group">
            <label for="edited_blogpost_title">Post Title</label>
            <input type="text" class="form-control" id="edited_blogpost_title" name="edited_blogpost_title" value="{{ selected_post.title }}" />
        </div>
        <div class="form-group">
            <label for="edited_blogpost_content">Post Content</label>
            <textarea class="form-control" id="edited_blogpost_content" name="edited_blogpost_content" rows="4">{{ selected_post.content }}</textarea>
        </div>
        <div>
            <p>Delete Post?</p>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="delete" id="delete_yes" value="yes">
                <label class="form-check-label" for="delete_yes">
                    Yes
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="delete" id="delete_no" value="no" checked>
                <label class="form-check-label" for="delete_no">
                    No
                </label>
            </div>
        </div>
        <input type="hidden" id="blogpost_id" name="blogpost_id" value="{{ selected_post.id }}" />
        <button type="submit" class="btn btn-primary">Edit Post</button>
    </form>
</div>
{% endblock content %}

app/templates/database/edit_component_element_form.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <form action="{{ url_for('database.edit_component_element') }}" id="edit_element_form">
        <div>
            <h5>Edit Element: {{ element.name }}</h5>
        </div>
        <div class="form-group">
            <label for="element_name">Name</label>
            <input type="text" class="form-control" id="element_name" name="element_name" value="{{ element.name }}" />
        </div>
        <div class="form-group">
            <label for="element_type">Type</label>
            <input type="text" class="form-control" id="element_type" name="element_type" value="{{ element.element_type }}" />
        </div>
        <div class="form-group">
            <label for="element_content">Content</label>
            <textarea class="form-control" id="element_content" name="element_content" rows="4">{{ element.content }}</textarea>
        </div>
        <div class="form-group">
            <label for="element_content">Value</label>
            <textarea class="form-control" id="element_value" name="element_value" rows="4">{{ element.value }}</textarea>
        </div>
        
        <input type="hidden" id="element_id" name="element_id" value="{{ element.id }}" />
        <button type="submit" class="btn btn-primary">Edit Element</button>
    </form>
</div>
{% endblock content %}

app/templates/database/edit_entities.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <h5 class="page_title">Edit Entities</h5>
</div>

<div class="row">
    <form action="{{ url_for('database.choose_blogpost') }}">
        <div>
            <h5>Edit Blog Post</h5>
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="blogpost_id">Blog Posts</label>
            </div>
            <select class="custom-select" id="blogpost_id" name="blogpost_id">
                {% for blog_post in blog_posts %}
                    <option value="{{ blog_post.id }}">{{ blog_post.title }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Select Post</button>
    </form>
    <form action="{{ url_for('database.choose_user') }}">
        <div>
            <h5>Edit User</h5>
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="user_id">Users</label>
            </div>
            <select class="custom-select" id="user_id" name="user_id">
                {% for user in users %}
                    <option value="{{ user.id }}">{{ user.username }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Select User</button>
    </form>
    <form action="{{ url_for('database.choose_project') }}">
        <div>
            <h5>Edit Project</h5>
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="project_id">Projects</label>
            </div>
            <select class="custom-select" id="project_id" name="project_id">
                {% for project in projects %}
                    <option value="{{ project.id }}">{{ project.name }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Select Project</button>
    </form>
</div>
{% endblock content %}

app/templates/database/edit_page_category_form.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <form action="{{ url_for('database.edit_page_category') }}" id="edit_category_form">
        <div>
            <h5>Edit Category: {{ category.name }}</h5>
        </div>
        <div class="form-group">
            <label for="category_name">Name</label>
            <input type="text" class="form-control" id="category_name" name="category_name" value="{{ category.name }}" />
        </div>
        
        <input type="hidden" id="category_id" name="category_id" value="{{ category.id }}" />
        <button type="submit" class="btn btn-primary">Edit Category</button>
    </form>
</div>
{% endblock content %}

app/templates/database/edit_page_component_form.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <form action="{{ url_for('database.edit_page_component') }}" id="edit_component_form">
        <div>
            <h5>Edit Component: {{ component.name }}</h5>
        </div>
        <div class="form-group">
            <label for="component_name">Name</label>
            <input type="text" class="form-control" id="component_name" name="component_name" value="{{ component.name }}" />
        </div>
        <div class="form-group">
            <label for="component_category">Type</label>
            <input type="text" class="form-control" id="component_component_type" name="component_component_type" value="{{ component.component_type }}" />
        </div>
        <div class="form-group">
            <label for="component_components">Elements</label>
            <input type="text" class="form-control" id="component_elements" name="component_elements" value="{% for element in component.elements %}{{ element.name }}, {% endfor %}" />
        </div>
        
        <input type="hidden" id="component_id" name="component_id" value="{{ component.id }}" />
        <button type="submit" class="btn btn-primary">Edit Component</button>
    </form>
</div>
{% endblock content %}

app/templates/database/edit_project.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <form action="{{ url_for('database.edit_project') }}" id="edit_blogpost_form">
        <div>
            <h5>Edit Project: {{ selected_project.name }}</h5>
        </div>
        <div class="form-group">
            <label for="edited_name">Name</label>
            <input type="text" class="form-control" id="edited_name" name="edited_name" value="{{ selected_project.name }}" />
        </div>
        <div class="form-group">
            <label for="edited_description">Description</label>
            <textarea class="form-control" id="edited_description" name="edited_description" rows="4">{{ selected_project.description }}</textarea>
        </div>
        <div class="form-group">
            <label for="edited_name">GitHub</label>
            <input type="text" class="form-control" id="edited_github" name="edited_github" value="{{ selected_project.github }}" />
        </div>
        <div>
            <p>Delete Project?</p>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="delete" id="delete_yes" value="yes">
                <label class="form-check-label" for="delete_yes">
                    Yes
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="delete" id="delete_no" value="no" checked>
                <label class="form-check-label" for="delete_no">
                    No
                </label>
            </div>
        </div>
        <input type="hidden" id="project_id" name="project_id" value="{{ selected_project.id }}" />
        <button type="submit" class="btn btn-primary">Edit Project</button>
    </form>
</div>
{% endblock content %}

app/templates/database/edit_tags.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <form action="{{ url_for('database.change_tags') }}" id="edit_tags_form">

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="selection_options">{{ selection_type }}</label>
            </div>
            <select class="custom-select" id="selection_options" name="object_id">
                {% if selection_type == "project" %}
                    {% for option in selection_options %}
                        <option value="{{ option.id }}">{{ option.name }}</option>
                    {% endfor %}
                {% endif %}
                {% if selection_type == 'blogpost' %}
                    {% for option in selection_options %}
                        <option value="{{ option.id }}">{{ option.title }}</option>
                    {% endfor %}
                {% endif %}
            </select>
        </div>

        <div class="form-group">
            <label for="edited_tags">Tags</label>
            <textarea class="form-control" id="edited_tags" name="new_tags" rows="4" placeholder="Tags separated by commas"></textarea>
        </div>

        <input type="hidden" id="object_type" name="object_type" value="{{ selection_type }}" />
        <button type="submit" class="btn btn-primary">Edit Tags</button>
    </form>
</div>
{% endblock content %}

app/templates/database/edit_user.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <form action="{{ url_for('database.edit_user') }}" id="edit_user_form">
        <div>
            <h5>Edit User: {{ selected_user.title }}</h5>
        </div>
        <div class="form-group">
            <label for="edited_username">Username</label>
            <input type="text" class="form-control" id="edited_username" name="edited_username" value="{{ selected_user.username }}" />
        </div>
        <div class="form-group">
            <label for="edited_password">Password</label>
            <input type="text" class="form-control" id="edited_password" name="edited_password" value="{{ selected_user.password }}" />
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="edited_role">Roles</label>
            </div>
            <select class="custom-select" id="edited_role" name="edited_role">
                {% for role in roles %}
                    <option value="{{ role.id }}">{{ role.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <p>Delete User?</p>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="delete" id="delete_yes" value="yes">
                <label class="form-check-label" for="delete_yes">
                    Yes
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="delete" id="delete_no" value="no" checked>
                <label class="form-check-label" for="delete_no">
                    No
                </label>
            </div>
        </div>
        <input type="hidden" id="user_id" name="user_id" value="{{ selected_user.id }}" />
        <button type="submit" class="btn btn-primary">Edit User</button>
    </form>
</div>
{% endblock content %}

app/templates/database/main.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <h5 class="page_title">Alexander Blair's Portfolio Database</h5>
    <p>This is the Database Page for Alexander Blair's Portfolio</p>
</div>

<div class="row">
    <ul>
        <a href="{{ url_for('database.new_entities') }}"> 
            <li>Create New Database Entries</li>
        </a>
        <a href="{{ url_for('database.edit_entities') }}"> 
            <li>Edit Database Entries</li>
        </a>
    </ul>
</div>

<div class="row">
    <ul>
        <a href="{{ url_for('database.v2_new_entities') }}"> 
            <li>V2 New Entities</li>
        </a>
        <a href="{{ url_for('database.v2_edit_entities') }}"> 
            <li>V2 Edit Entities</li>
        </a>
    </ul>
</div>
{% endblock content %}

app/templates/database/new_entities.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
<h5 class="page_title">Alexander Blair's Portfolio Database</h5>
</div>

<div class="row">
    <form action="{{ url_for('database.create_role') }}">
        <div>
            <h5>Create New Role</h5>
        </div>
        <div class="form-group">
            <label for="role_name">Role Name</label>
            <input type="text" class="form-control" id="role_name" name="role_name" placeholder="Administrator, User, Guest, etc." />
        </div>
        <button type="submit" class="btn btn-primary">Create Role</button>
    </form>
</div>
<hr />

<div class="row">
    <form action="{{ url_for('database.create_user') }}">
        <div>
            <h5>Create New User</h5>
        </div>
        <div class="form-group">
            <label for="role_name">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Username" />
        </div>
        <div class="form-group">
            <label for="role_name">Password</label>
            <input type="password" class="form-control" id="password" name="password" />
        </div>
        <div class="form-group">
            <label for="role_name">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="person@email.com" />
        </div>
        <div class="form-group">
            <label for="role_name">Role ID</label>
            <input type="text" class="form-control" id="role_id" name="role_id" placeholder="4, 5, 6" />
        </div>
        <button type="submit" class="btn btn-primary">Create User</button>
    </form>
</div>
<hr />

<div class="row">
    <form action="{{ url_for('database.create_project') }}">
        <div>
            <h5>Create New Project</h5>
        </div>
        <div class="form-group">
            <label for="role_name">Name</label>
            <input type="text" class="form-control" id="project_name" name="project_name" placeholder="Project Name" />
        </div>
        <div class="form-group">
            <label for="role_name">Description</label>
            <input type="text-area" class="form-control" id="project_description" name="project_description" placeholder="Project Description" />
        </div>
        <div class="form-group">
            <label for="role_name">GitHub</label>
            <input type="text" class="form-control" id="project_github" name="project_github" placeholder="GitHub Repository" />
        </div>
        <button type="submit" class="btn btn-primary">Create Project</button>
    </form>
</div>
<hr />

<div class="row">
    <form action="{{ url_for('database.create_blogpost') }}">
        <div>
            <h5>Create New Blog Post</h5>
        </div>
        <div class="form-group">
            <label for="role_name">Title</label>
            <input type="text" class="form-control" id="blogpost_title" name="blogpost_title" placeholder="Blog Post Title" />
        </div>
        <div class="form-group">
            <label for="role_name">Content</label>
            <input type="text-area" class="form-control" id="blogpost_content" name="blogpost_content" placeholder="Blog Post Content" />
        </div>
        <div class="form-group">
            <label for="role_name">Author ID</label>
            <input type="text" class="form-control" id="blogpost_author" name="blogpost_author" placeholder="Author ID" />
        </div>
        <button type="submit" class="btn btn-primary">Create Blog Post</button>
    </form>
</div>
<hr />

<div class="row">
    <form action="{{ url_for('database.create_tag') }}">
        <div>
            <h5>Create New Tag</h5>
        </div>
        <div class="form-group">
            <label for="tag_name">Tag Name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="Python, JavaScript, Flask, etc." />
        </div>
        <button type="submit" class="btn btn-primary">Create Tag</button>
    </form>
</div>
<hr />
{% endblock content %}

app/templates/database/v2_new_entities.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
<h5 class="page_title">Portfolio API V2</h5>
</div>


<!-- Create New Element -->
<div class="row">
    <form action="{{ url_for('database.create_page') }}">
        <div>
            <h5>New Page</h5>
        </div>
        <div class="form-group">
            <label for="page_name">Page Name</label>
            <input type="text" class="form-control" id="page_name" name="page_name" />
        </div>
        <div class="form-group">
            <label for="page_category">Category (Name)</label>
            <input type="text" class="form-control" id="page_category" name="page_category" />
        </div>
        <div class="form-group">
            <label for="page_components">Components (Name)</label>
            <input type="text" class="form-control" id="page_components" name="page_components" />
        </div>
        <button type="submit" class="btn btn-primary">Create Page</button>
    </form>
</div>
<hr />

<div class="row">
    <form action="{{ url_for('database.create_page_category') }}">
        <div>
            <h5>New Page Category</h5>
        </div>
        <div class="form-group">
            <label for="category_name">Name</label>
            <input type="text" class="form-control" id="category_name" name="category_name" />
        </div>
        <button type="submit" class="btn btn-primary">Create Category</button>
    </form>
</div>
<hr />

<div class="row">
    <form action="{{ url_for('database.create_page_component') }}">
        <div>
            <h5>New Component</h5>
        </div>
        <div class="form-group">
            <label for="component_name">Name</label>
            <input type="text" class="form-control" id="component_name" name="component_name" />
        </div>
        <div class="form-group">
            <label for="component_type">Type</label>
            <input type="text" class="form-control" id="component_type" name="component_type" />
        </div>
        <div class="form-group">
            <label for="component_elements">Elements (By Name)</label>
            <input type="text" class="form-control" id="component_elements" name="component_elements" />
        </div>
        <button type="submit" class="btn btn-primary">Create Component</button>
    </form>
</div>
<hr />

<div class="row">
    <form action="{{ url_for('database.create_component_element') }}">
        <div>
            <h5>New Element</h5>
        </div>
        <div class="form-group">
            <label for="element_name">Name</label>
            <input type="text" class="form-control" id="element_name" name="element_name" />
        </div>
        <div class="form-group">
            <label for="element_content">Content</label>
            <input type="text-area" class="form-control" id="element_content" name="element_content" placeholder="Element Content" />
        </div>
        <div class="form-group">
            <label for="element_type">Type</label>
            <input type="text" class="form-control" id="element_type" name="element_type" placeholder="title, link, text, etc." />
        </div>
        <div class="form-group">
            <label for="element_value">Value</label>
            <input type="text" class="form-control" id="element_value" name="element_value" placeholder="url, page_id, value significant to type" />
        </div>
        <button type="submit" class="btn btn-primary">Create Element</button>
    </form>
</div>
<hr />
{% endblock content %}